# Generated by Django 2.1 on 2018-10-31 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=10, verbose_name='岗位名称')),
                ('position_type', models.CharField(choices=[('科研', '科研'), ('设计', '设计'), ('集成', '集成'), ('测试', '测试'), ('市场', '市场'), ('管理', '管理')], default='综合管理', max_length=10, verbose_name='岗位类型')),
                ('apply_type', models.CharField(choices=[('校园招聘', '校园招聘'), ('社会招聘', '社会招聘')], default='社会招聘', max_length=10, verbose_name='招聘类型')),
                ('company', models.CharField(choices=[('总部', '总部'), ('北京分公司', '北京分公司'), ('上海分公司', '上海分公司'), ('成都分公司', '成都分公司'), ('沈阳分公司', '沈阳分公司'), ('广州分公司', '广州分公司'), ('武汉分公司', '武汉分公司'), ('西安分公司', '西安分公司'), ('新疆分公司', '新疆分公司'), ('济南分公司', '济南分公司'), ('昆明分公司', '昆明分公司'), ('兰州分公司', '兰州分公司'), ('南昌分公司', '南昌分公司'), ('南宁分公司', '南宁分公司'), ('郑州分公司', '郑州分公司')], default='总部', max_length=20, verbose_name='所属公司')),
                ('location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('成都', '成都'), ('沈阳', '沈阳'), ('广州', '广州'), ('武汉', '武汉'), ('西安', '西安'), ('新疆', '新疆'), ('济南', '济南'), ('昆明', '昆明'), ('兰州', '兰州'), ('南昌', '南昌'), ('南宁', '南宁'), ('郑州', '郑州')], default='北京', max_length=10, verbose_name='工作地')),
                ('department', models.CharField(max_length=20, verbose_name='所属部门')),
                ('pub_date', models.DateField(verbose_name='发布时间')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='到期时间')),
                ('exp_req', models.IntegerField(choices=[(0, '应届生'), (1, '一年以上'), (2, '二年以上'), (3, '三年以上'), (4, '四年以上'), (5, '五年以上'), (6, '六年以上'), (7, '七年以上'), (8, '八年以上'), (9, '九年以上'), (10, '十年以上')], default=0, verbose_name='工作年限')),
                ('edu_req', models.CharField(choices=[('本科', '本科'), ('研究生', '研究生'), ('博士生', '博士生'), ('专科', '专科'), ('不限', '不限')], default=0, max_length=10, verbose_name='学历要求')),
                ('num', models.IntegerField(default=1, verbose_name='招聘人数')),
                ('position_detail', models.TextField(max_length=500, verbose_name='岗位描述')),
                ('position_req', models.TextField(max_length=500, verbose_name='岗位要求')),
                ('apply_num', models.IntegerField(default=0, verbose_name='应聘人数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('is_delete', models.BooleanField(default=1, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '岗位管理',
            },
        ),
        migrations.CreateModel(
            name='PositionApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='申请中', max_length=10)),
                ('is_delete', models.BooleanField(default=0)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='position.Position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PositionFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='已收藏', max_length=10)),
                ('is_delete', models.BooleanField(default=0)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_fav_foreignkey', to='position.Position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
