# Generated by Django 2.1 on 2018-08-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_userinfo_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_pwd',
            field=models.CharField(max_length=50),
        ),
    ]
