# Generated by Django 2.1 on 2018-08-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180813_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('validation', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
