# Generated by Django 2.1 on 2018-09-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='photo',
            field=models.ImageField(null=True, upload_to='center/photo'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='resume',
            field=models.FileField(null=True, upload_to='center/resume'),
        ),
    ]
