# Generated by Django 2.1 on 2018-09-28 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='reserved_info01',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注1'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='reserved_info02',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注2'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='reserved_info03',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注3'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='reserved_info04',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注4'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='reserved_info05',
            field=models.IntegerField(null=True, verbose_name='备注5'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='user',
            field=models.OneToOneField(default=99, on_delete=django.db.models.deletion.CASCADE, related_name='basicinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
