# Generated by Django 2.1 on 2018-09-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20180906_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='center/photo'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='reserved_info01',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='reserved_info02',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='reserved_info03',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='reserved_info04',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='reserved_info05',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='center/resume'),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='reserved_info10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='reserved_info11',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='reserved_info12',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='reserved_info13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='reserved_info06',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='reserved_info07',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='reserved_info08',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='reserved_info09',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
