# Generated by Django 2.1 on 2018-09-29 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20180928_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='resume_create_time',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='resume_update_time',
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basicinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
