# Generated by Django 2.1 on 2018-09-30 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_auto_20180929_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eduinfo',
            name='edu_foreignkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_info', to='center.BasicInfo'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='work_foreignkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_info', to='center.BasicInfo'),
        ),
    ]
