# Generated by Django 2.1 on 2018-10-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_auto_20180930_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/', verbose_name='简历')),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='resume',
        ),
    ]
