# Generated by Django 2.1 on 2018-10-11 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('center', '0007_auto_20181011_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumefile',
            name='user',
            field=models.OneToOneField(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='resume_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
