# Generated by Django 2.1 on 2018-10-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_number',
        ),
        migrations.AddField(
            model_name='post',
            name='num_requirement',
            field=models.IntegerField(default=99, verbose_name='招聘人数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.CharField(max_length=20, verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='post',
            name='edu_requirement',
            field=models.CharField(max_length=10, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='post',
            name='exp_requirement',
            field=models.CharField(max_length=10, verbose_name='工作年限'),
        ),
        migrations.AlterField(
            model_name='post',
            name='expire_time',
            field=models.DateField(verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=6, verbose_name='工作地'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_company',
            field=models.CharField(max_length=20, verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(max_length=10, verbose_name='岗位名称'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_requirement',
            field=models.TextField(max_length=500, verbose_name='岗位要求'),
        ),
        migrations.AlterField(
            model_name='post',
            name='release_time',
            field=models.DateField(verbose_name='发布之间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='responsibility',
            field=models.TextField(max_length=500, verbose_name='岗位描述'),
        ),
    ]
