# Generated by Django 2.1 on 2018-10-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20181011_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num_requirement',
            field=models.IntegerField(default=1, verbose_name='招聘人数'),
        ),
    ]
