# Generated by Django 2.1 on 2018-10-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20181011_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_company',
        ),
        migrations.AddField(
            model_name='post',
            name='company',
            field=models.CharField(choices=[('总部', '总部'), ('北京分公司', '北京分公司'), ('上海分公司', '上海分公司'), ('成都分公司', '成都分公司'), ('沈阳分公司', '沈阳分公司'), ('广州分公司', '广州分公司'), ('武汉分公司', '武汉分公司'), ('西安分公司', '西安分公司'), ('新疆分公司', '新疆分公司'), ('济南分公司', '济南分公司'), ('昆明分公司', '昆明分公司'), ('兰州分公司', '兰州分公司'), ('南昌分公司', '南昌分公司'), ('南宁分公司', '南宁分公司'), ('郑州分公司', '郑州分公司')], default='总部', max_length=20, verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='post',
            name='edu_requirement',
            field=models.CharField(choices=[('本科', '本科'), ('研究生', '研究生'), ('博士生', '博士生'), ('专科', '专科'), ('不限', '不限')], default=0, max_length=10, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='post',
            name='exp_requirement',
            field=models.IntegerField(choices=[(0, '应届毕业生'), (1, '一年以上'), (2, '二年以上'), (3, '三年以上'), (4, '四年以上'), (5, '五年以上'), (6, '六年以上'), (7, '七年以上'), (8, '八年以上'), (9, '九年以上'), (10, '十年以上')], default=0, max_length=10, verbose_name='工作年限'),
        ),
    ]
