# Generated by Django 2.1 on 2018-10-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20181011_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='num_requirement',
            new_name='num',
        ),
        migrations.AlterField(
            model_name='post',
            name='exp_requirement',
            field=models.IntegerField(choices=[(0, '应届毕业生'), (1, '一年以上'), (2, '二年以上'), (3, '三年以上'), (4, '四年以上'), (5, '五年以上'), (6, '六年以上'), (7, '七年以上'), (8, '八年以上'), (9, '九年以上'), (10, '十年以上')], default=0, verbose_name='工作年限'),
        ),
        migrations.AlterField(
            model_name='post',
            name='expire_time',
            field=models.DateField(blank=True, null=True, verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='release_time',
            field=models.DateField(verbose_name='发布时间'),
        ),
    ]
