# Generated by Django 2.1 on 2018-10-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20181011_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='apply_num',
            field=models.IntegerField(default=0, verbose_name='应聘人数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='exp_requirement',
            field=models.IntegerField(choices=[(0, '应届生'), (1, '一年以上'), (2, '二年以上'), (3, '三年以上'), (4, '四年以上'), (5, '五年以上'), (6, '六年以上'), (7, '七年以上'), (8, '八年以上'), (9, '九年以上'), (10, '十年以上')], default=0, verbose_name='工作年限'),
        ),
    ]
