# Generated by Django 2.1 on 2018-10-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='expire_time',
            new_name='expire_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='release_time',
            new_name='public_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='edu_requirement',
            field=models.CharField(choices=[('本科', '本科'), ('研究生', '研究生'), ('博士生', '博士生'), ('专科', '专科'), ('不限', '不限')], default=0, max_length=10, verbose_name='学历要求'),
        ),
    ]
