# Generated by Django 2.1 on 2018-10-12 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_applyinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='responsibility',
            new_name='responsibilities',
        ),
    ]
