# Generated by Django 2.1 on 2018-10-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20181012_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('科研开发', '科研开发'), ('设计专业', '设计专业'), ('系统集成', '系统集成'), ('测试专业', '测试专业'), ('市场经营', '市场经营'), ('生产售后', '生产售后'), ('综合管理', '综合管理'), ('人力资源', '人力资源'), ('财务', '财务'), ('采购', '采购'), ('法律合规', '法律合规'), ('科学研究', '科学研究'), ('战略规划', '战略规划'), ('博士后', '博士后'), ('海外市场', '海外市场'), ('项目管理', '项目管理')], default='综合管理', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_delete',
            field=models.BooleanField(default=1),
        ),
    ]
