# Generated by Django 2.1 on 2018-10-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20181012_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyinfo',
            name='count',
        ),
        migrations.AddField(
            model_name='applyinfo',
            name='apply_count',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='applyinfo',
            name='store_count',
            field=models.BooleanField(default=0),
        ),
    ]
