# Generated by Django 2.1 on 2018-10-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20181016_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='store_num',
            field=models.IntegerField(default=0, verbose_name='收藏人数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
