# Generated by Django 2.1 on 2018-10-16 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0016_auto_20181016_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinfo',
            name='post',
        ),
        migrations.RemoveField(
            model_name='storeinfo',
            name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='store_num',
            new_name='fav_num',
        ),
        migrations.AddField(
            model_name='post',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='applicants',
            field=models.ManyToManyField(related_name='applicants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StoreInfo',
        ),
    ]
