# Generated by Django 2.1 on 2018-10-17 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0018_auto_20181017_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_status', models.CharField(default='未申请', max_length=10)),
                ('apply_count', models.IntegerField(default=0)),
                ('post_foreignkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_apply_foreignkey', to='post.Post')),
                ('user_foreignkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_status', models.CharField(default='未申请', max_length=10)),
                ('apply_count', models.IntegerField(default=0)),
                ('post_foreignkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_fav_foreignkey', to='post.Post')),
                ('user_foreignkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
