# Generated by Django 2.1 on 2018-10-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_postapply_postfav'),
    ]

    operations = [
        migrations.AddField(
            model_name='postapply',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='postfav',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
