# Generated by Django 2.1 on 2018-10-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20181017_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postapply',
            name='apply_count',
        ),
        migrations.RemoveField(
            model_name='postfav',
            name='apply_count',
        ),
        migrations.RemoveField(
            model_name='postfav',
            name='apply_status',
        ),
        migrations.AddField(
            model_name='postfav',
            name='fav_status',
            field=models.CharField(default='未收藏', max_length=10),
        ),
    ]
