# Generated by Django 2.1 on 2018-10-18 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20181017_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postapply',
            name='post_foreignkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.Post'),
        ),
    ]
