# Generated by Django 2.1 on 2018-10-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20181018_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postapply',
            old_name='post_foreignkey',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postapply',
            old_name='apply_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='postapply',
            old_name='user_foreignkey',
            new_name='user',
        ),
    ]
