# Generated by Django 2.1 on 2018-10-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_auto_20181018_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_delete',
            field=models.BooleanField(default=1, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[(0, '北京'), (1, '上海'), (2, '成都'), (3, '沈阳'), (4, '广州'), (5, '武汉'), (6, '西安'), (7, '新疆'), (8, '济南'), (9, '昆明'), (10, '兰州'), (11, '南昌'), (12, '南宁'), (13, '郑州')], default='北京', max_length=10, verbose_name='工作地'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('科研', '科研'), ('设计', '设计'), ('集成', '集成'), ('测试', '测试'), ('市场', '市场'), ('管理', '管理')], default='综合管理', max_length=10, verbose_name='岗位类型'),
        ),
        migrations.AlterField(
            model_name='postapply',
            name='status',
            field=models.CharField(default='申请中', max_length=10),
        ),
        migrations.AlterField(
            model_name='postfav',
            name='status',
            field=models.CharField(default='已收藏', max_length=10),
        ),
    ]
