# Generated by Django 2.1 on 2018-10-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_auto_20181030_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.IntegerField(choices=[(0, '北京'), (1, '上海'), (2, '成都'), (3, '沈阳'), (4, '广州'), (5, '武汉'), (6, '西安'), (7, '新疆'), (8, '济南'), (9, '昆明'), (10, '兰州'), (11, '南昌'), (12, '南宁'), (13, '郑州')], default=0, verbose_name='工作地'),
        ),
    ]
