# Generated by Django 2.1 on 2018-10-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_auto_20181030_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('成都', '成都'), ('沈阳', '沈阳'), ('广州', '广州'), ('武汉', '武汉'), ('西安', '西安'), ('新疆', '新疆'), ('济南', '济南'), ('昆明', '昆明'), ('兰州', '兰州'), ('南昌', '南昌'), ('南宁', '南宁'), ('郑州', '郑州')], default='北京', max_length=10, verbose_name='工作地'),
        ),
    ]
