# Generated by Django 2.1 on 2018-10-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_auto_20181030_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='expire_date',
            new_name='exp_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='public_date',
            new_name='pub_date',
        ),
    ]
